CREATE TABLE vitals (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  patient_id   NUMBER,
  bp_high      NUMBER,
  bp_low       NUMBER,
  spo2         NUMBER,
  recorded_on  TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINT fk_patient FOREIGN KEY (patient_id) REFERENCES patient(id)
);
SELECT table_name FROM user_tables;
SELECT owner, table_name FROM all_tables WHERE table_name LIKE '%DOCTOR%';
SELECT * FROM all_tables WHERE owner = 'SYSTEM'; 
DESC doctor;
 -- or your username in UPPERCASE


